In [ ]:
import numpy as np

In [ ]:
pd.options.display.max_rows = 170

Checking if there is nan data after normalising and padding

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_pickle("/content/drive/MyDrive/Colab Notebooks/ROIxTimeseries/psi_data.pkl")

In [ ]:
data

subject                                         psi_matrix  adhd  \
0      subject1  [[1.0, 0.8016814987579317, 0.839641852247262, ...     0   
1      subject2  [[1.0, 0.9101210641534417, 0.576123749895304, ...     0   
2      subject3  [[1.0, 0.7530150385517623, 0.5067414702685676,...     0   
3      subject4  [[1.0, 0.817812140965262, 0.520061068095793, 0...     0   
4      subject5  [[1.0, 0.7477157295145737, 0.8259250654415865,...     0   
5      subject6  [[1.0, 0.817826856928272, 0.7610129909414917, ...     0   
6      subject7  [[1.0, 0.8984681416784894, 0.7487034503635821,...     0   
7      subject8  [[1.0, 0.8660934325896603, 0.695766272463877, ...     0   
8      subject9  [[1.0, 0.8935908810731377, 0.7417437154853028,...     0   
9     subject10  [[1.0, 0.5276029984267508, 0.574830077380396, ...     0   
10    subject11  [[1.0, 0.8512941492336905, 0.7079565876124402,...     0   
11    subject12  [[1.0, 0.7767769004513064, 0.6059687178891598,...     0   
12    subject13  [[1.0, 0.6893767753039011, 0.199999491916602, ...     0   
13    subject14  [[1.0, 0.6217638325381483, 0.673140801338815, ...     0   
14    subject15  [[1.0, 0.7507598435618418, 0.67933409306654, 0...     0   
15    subject16  [[1.0, 0.9274449772194566, 0.7070753261309272,...     0   
16    subject17  [[1.0, 0.7013375151145338, 0.7056282925983179,...     0   
17    subject18  [[1.0, 0.8633703953076712, 0.4970408637389306,...     0   
18    subject19  [[1.0, 0.8097249746262883, 0.6863674092638138,...     0   
19    subject20  [[1.0, 0.9466888699264099, 0.7758158191611573,...     0   
20    subject21  [[1.0, 0.9323941253615073, 0.8436276470061118,...     0   
21    subject22  [[1.0, 0.6069863064646017, 0.4433270516649374,...     0   
22    subject23  [[1.0, 0.5801276394682083, 0.4118945786175999,...     0   
23    subject24  [[1.0, 0.7192205593868304, 0.549497754523786, ...     0   
24    subject25  [[1.0, 0.7974734629214292, 0.7514448974572986,...     0   
25    subject26  [[1.0, 0.6099895151333957, 0.4059478169721132,...     0   
26    subject27  [[1.0, 0.8399023608069939, 0.7127936309789397,...     0   
27    subject28  [[1.0, 0.6691535061607642, 0.6415259031401145,...     0   
28    subject29  [[1.0, 0.8476687684838936, 0.6821188598180312,...     0   
29    subject30  [[1.0, 0.7295996800419383, 0.5719806951785374,...     0   
30    subject31  [[1.0, 0.5867443057857676, 0.5526965992128333,...     0   
31    subject32  [[1.0, 0.6778086344664657, 0.6467085432635119,...     0   
32    subject33  [[1.0, 0.9606131804284284, 0.8481746014844914,...     0   
33    subject34  [[1.0, 0.7167088793977963, 0.5440363223456469,...     0   
34    subject35  [[1.0, 0.5738811723592999, 0.6235762728938389,...     0   
35    subject36  [[1.0, 0.7916590106114967, 0.4891452654333689,...     0   
36    subject37  [[1.0, 0.47610696033285443, 0.4962532891903924...     0   
37    subject38  [[1.0, 0.8773725510270401, 0.6915104853939901,...     0   
38    subject39  [[1.0, 0.9035458431663922, 0.6022329005931537,...     0   
39    subject40  [[1.0, 0.8701051865292525, 0.7517256425385658,...     0   
40    subject41  [[1.0, 0.8826314804027245, 0.7216112608073401,...     0   
41    subject42  [[1.0, 0.7900257682577474, 0.644414401693302, ...     0   
42    subject43  [[1.0, 0.8843944556143615, 0.6650576355320952,...     0   
43    subject44  [[1.0, 0.7922789649399362, 0.7268425044671274,...     0   
44    subject45  [[1.0, 0.6782153920036078, 0.2693052063273565,...     0   
45    subject46  [[1.0, 0.5693514827469509, 0.23784783684269262...     0   
46    subject47  [[1.0, 0.8634769083950957, 0.758313172841575, ...     0   
47    subject48  [[1.0, 0.7280731807806998, 0.4261665729361692,...     0   
48    subject49  [[1.0, 0.7123081070017526, 0.6329145608107885,...     0   
49    subject50  [[1.0, 0.6810314596914553, 0.5437724782680083,...     0   
50    subject51  [[1.0, 0.76694330966328, 0.6248807849571782, 0...     0   
51    subject52  [[1.0, 0.8841019458433531, 0.6310939099

In [ ]:
d1 = pd.read_pickle('/content/drive/MyDrive/Colab Notebooks/RRC_FcMaps/FCmaps_data.pkl')

In [ ]:
d1

subject                                              fcmap  adhd  \
0      subject1  [[nan, 0.5238301930931133, -0.2282216203110824...     0   
1      subject2  [[nan, 0.4748539075236425, 0.04488964356167748...     0   
2      subject3  [[nan, -0.3223992385318596, -0.017720272215859...     0   
3      subject4  [[nan, 0.29769854683773916, -0.024657165451793...     0   
4      subject5  [[nan, 0.5938212810274702, 0.01331333354518493...     0   
5      subject6  [[nan, 0.5274409022953241, 0.35528281639904413...     0   
6      subject7  [[nan, 0.7684778461215634, -0.0792584228013906...     0   
7      subject8  [[nan, 0.5045380789518739, 0.10549870833265854...     0   
8      subject9  [[nan, 0.6216719888844139, 0.11048418621686452...     0   
9     subject10  [[nan, 0.1483531920748262, -0.1031453978960041...     0   
10    subject11  [[nan, 0.4686439824073208, 0.20512305684065726...     0   
11    subject12  [[nan, 0.42317554132024765, -0.074112962151799...     0   
12    subject13  [[nan, 0.3665985707293383, -0.0655667223607365...     0   
13    subject14  [[nan, 0.33046939541359266, -0.017769057507488...     0   
14    subject15  [[nan, 0.4613538129794794, -0.0125000896979156...     0   
15    subject16  [[nan, 0.8373749803157527, 0.02244955614667427...     0   
16    subject17  [[nan, 0.2897282666048168, 0.18432085812054316...     0   
17    subject18  [[nan, 0.7281595730966794, 0.00238016349167070...     0   
18    subject19  [[nan, 0.5843657144914735, 0.11987164541145874...     0   
19    subject20  [[nan, 0.2523306280171711, 0.28797542857910496...     0   
20    subject21  [[nan, 0.6278944023045546, 0.5165028538694347,...     0   
21    subject22  [[nan, 0.13785666073184086, 0.2547004619162932...     0   
22    subject23  [[nan, 0.14911024291650884, 0.0079333601447855...     0   
23    subject24  [[nan, 0.3764648954309314, 0.08600924516744045...     0   
24    subject25  [[nan, 0.42174944188364305, 0.3165272370750452...     0   
25    subject26  [[nan, 0.1805143649862001, -0.2348731377071997...     0   
26    subject27  [[nan, 0.45535307904933, -0.00415143033090804,...     0   
27    subject28  [[nan, 0.22971464041591738, 0.0109179332737702...     0   
28    subject29  [[nan, 0.5376934177961351, 0.01960199000005619...     0   
29    subject30  [[nan, 0.4056091197958261, -0.2925733521082982...     0   
30    subject31  [[nan, 0.3542140642176268, -0.5914321867220893...     0   
31    subject32  [[nan, 0.22048568767157498, 0.2039162073894712...     0   
32    subject33  [[nan, 0.5055810155709716, -0.2521104625219292...     0   
33    subject34  [[nan, 0.26329072532420517, 0.0113868270074488...     0   
34    subject35  [[nan, 0.18930322230206809, 0.3632087743046964...     0   
35    subject36  [[nan, 0.8179272761858866, -0.2638524804791795...     0   
36    subject37  [[nan, -0.09286775997179725, 0.027596233140853...     0   
37    subject38  [[nan, 0.3856820227616622, 0.05713815475095538...     0   
38    subject39  [[nan, 0.9432973674668181, -0.3290745432473454...     0   
39    subject40  [[nan, 0.5394814631916641, 0.10014504321104824...     0   
40    subject41  [[nan, 0.7134169827167727, -0.0520712877161635...     0   
41    subject42  [[nan, 0.5677346440315646, 0.13704329898328788...     0   
42    subject43  [[nan, 0.7260830064401883, -0.1077076402715137...     0   
43    subject44  [[nan, 0.8899012796060446, -0.0556922233910135...     0   
44    subject45  [[nan, 0.20083331342328048, 0.1776948567645945...     0   
45    subject46  [[nan, 0.5039121561605981, -0.1731329805258499...     0   
46    subject47  [[nan, 0.8724866253342939, 0.08298900895659767...     0   
47    subject48  [[nan, 0.8105435410421713, 0.14576149903005878...     0   
48    subject49  [[nan, 0.2126857490053719, 0.2686816497603249,...     0   
49    subject50  [[nan, 0.20426982996768986, -0.085319223951297...     0   
50    subject51  [[nan, 1.0792533861270235, 0.13789049739722034...     0   
51    subject52  [[nan, 0.40599392865155925, -0.15584176

In [ ]:
# Replacing nan values to 1
def nan_to_0(data):

    df1 = data.copy()

    for idx, row in df1.iterrows():
      arr = row['fcmap']
      matrix = np.nan_to_num(arr, copy = True, nan = 0.0)
      df1.at[idx, 'fcmap'] = matrix

    print(df1)

    return df1

In [ ]:
df0 = nan_to_0(d1)

        subject                                              fcmap  adhd  \
0      subject1  [[0.0, 0.5238301930931133, -0.2282216203110824...     0   
1      subject2  [[0.0, 0.4748539075236425, 0.04488964356167748...     0   
2      subject3  [[0.0, -0.3223992385318596, -0.017720272215859...     0   
3      subject4  [[0.0, 0.29769854683773916, -0.024657165451793...     0   
4      subject5  [[0.0, 0.5938212810274702, 0.01331333354518493...     0   
5      subject6  [[0.0, 0.5274409022953241, 0.35528281639904413...     0   
6      subject7  [[0.0, 0.7684778461215634, -0.0792584228013906...     0   
7      subject8  [[0.0, 0.5045380789518739, 0.10549870833265854...     0   
8      subject9  [[0.0, 0.6216719888844139, 0.11048418621686452...     0   
9     subject10  [[0.0, 0.1483531920748262, -0.1031453978960041...     0   
10    subject11  [[0.0, 0.4686439824073208, 0.20512305684065726...     0   
11    subject12  [[0.0, 0.42317554132024765, -0.074112962151799...     0   
12    subjec

In [ ]:
def computeMinMax(X):
  min_matrix = X.min(axis = 0)
  max_matrix = X.max(axis = 0)
  return (min_matrix, max_matrix)

In [ ]:
def normalize_instance(X, minn, maxx):
  normalised_X = np.zeros(shape=(X.shape[0], X.shape[1]))

  for idx, x in np.ndenumerate(X):
    if minn[idx] == maxx[idx]:
      normalised_X[idx] = x
    else:
      normalised_X[idx] = (x - minn[idx])/(maxx[idx] - minn[idx])
    return normalised_X

In [ ]:
def normalize(df):
    # Extract the 'fcmap' column as a NumPy array
    X = df['fcmap'].values

    # Convert the matrices to a 2D NumPy array
    X_2d = np.stack(X)

    min_matrix, max_matrix = computeMinMax(X_2d)

    print("shape of min matrix", min_matrix.shape)
    print(min_matrix)
    print("shape of max matrix", max_matrix.shape)
    print(max_matrix)

    normalized_instances = []
    for instance in X_2d:
        normalized_instance = normalize_instance(instance, min_matrix, max_matrix)
        print(normalized_instance)
        normalized_instances.append(normalized_instance)

    # Convert the list of normalized instances to a NumPy array
    X_normalized_2d = np.array(normalized_instances)

    # Create a new DataFrame with the updated 'fcmap' column
    df_normalized = df.copy()
    # df_normalized['fcmap'] = X_normalized_2d
    df_normalized['fcmap'] = [X_normalized_2d[i].reshape(instance.shape) for i, instance in enumerate(X)]

    return df_normalized

In [ ]:
df_norm = normalize(df0)

shape of min matrix (132, 132)
[[ 0.         -0.32359152 -0.59143219 ... -0.44967196 -0.36007467
  -0.50361491]
 [-0.32359152  0.         -0.61034619 ... -0.50271673 -0.4416556
  -0.42971673]
 [-0.59143219 -0.61034619  0.         ... -0.54053901 -0.50141808
  -0.33857454]
 ...
 [-0.44967196 -0.50271673 -0.54053901 ...  0.         -0.10808939
  -0.41897515]
 [-0.36007467 -0.4416556  -0.50141808 ... -0.10808939  0.
  -0.34978241]
 [-0.50361491 -0.42971673 -0.33857454 ... -0.41897515 -0.34978241
   0.        ]]
shape of max matrix (132, 132)
[[0.         1.1574887  0.54338009 ... 0.41903948 0.4918872  0.45077198]
 [1.1574887  0.         0.42380102 ... 0.59414395 0.45637194 0.32140414]
 [0.54338009 0.42380102 0.         ... 0.54565136 0.50137854 0.48689823]
 ...
 [0.41903948 0.59414395 0.54565136 ... 0.         0.68709261 0.5072548 ]
 [0.4918872  0.45637194 0.50137854 ... 0.68709261 0.         0.72773342]
 [0.45077198 0.32140414 0.48689823 ... 0.5072548  0.72773342 0.        ]]
[[0. 0. 0. 

In [ ]:
df_norm

subject                                              fcmap  adhd  \
0      subject1  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
1      subject2  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
2      subject3  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
3      subject4  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
4      subject5  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
5      subject6  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
6      subject7  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
7      subject8  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
8      subject9  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
9     subject10  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
10    subject11  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
11    subject12  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
12    subject13  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
13    subject14  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
14    subject15  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
15    subject16  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
16    subject17  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
17    subject18  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
18    subject19  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
19    subject20  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
20    subject21  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
21    subject22  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
22    subject23  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
23    subject24  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
24    subject25  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
25    subject26  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
26    subject27  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
27    subject28  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
28    subject29  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
29    subject30  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
30    subject31  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
31    subject32  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
32    subject33  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
33    subject34  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
34    subject35  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
35    subject36  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
36    subject37  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
37    subject38  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
38    subject39  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
39    subject40  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
40    subject41  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
41    subject42  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
42    subject43  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
43    subject44  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
44    subject45  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
45    subject46  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
46    subject47  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
47    subject48  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
48    subject49  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
49    subject50  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
50    subject51  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
51    subject52  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.

In [ ]:
a = df_norm.iloc[151,1]

In [ ]:
import pandas as pd
a = pd.DataFrame(a)

In [ ]:
a.to_csv('norm_data.csv')

Stacking psi + fcmap matrices

In [ ]:
import numpy as np
import pandas as pd

# Assuming both dataframes have the same number of rows
combined_matrices = []

for i in range(len(data)):
    fcmap_matrix = df_norm.iloc[i]['fcmap']
    psi_matrix = data.iloc[i]['psi_matrix']

    # Stack the matrices along a new axis (axis=2) to create a 3D matrix
    combined_matrix = np.stack((fcmap_matrix, psi_matrix), axis=2)

    combined_matrices.append(combined_matrix)

# Create a new dataframe with the combined matrices
new_df = pd.DataFrame({
    'subject': data['subject'],
    'combined_matrix': combined_matrices,
    'autism': data['autism'],
    'adhd': data['adhd'],
    'healthy': data['healthy']
})

In [ ]:
m1 = new_df.iloc[111,1]

In [ ]:
print(type(m1))

<class 'numpy.ndarray'>


In [ ]:
m1.shape

(132, 132, 2)

In [ ]:
m1

array([[[0.        , 1.        ],
        [0.        , 0.87560901],
        [0.        , 0.75704277],
        ...,
        [0.        , 0.80361585],
        [0.        , 0.81343049],
        [0.        , 0.65461509]],

       [[0.        , 0.87560901],
        [0.        , 1.        ],
        [0.        , 0.71101762],
        ...,
        [0.        , 0.74293529],
        [0.        , 0.73955261],
        [0.        , 0.61440825]],

       [[0.        , 0.75704277],
        [0.        , 0.71101762],
        [0.        , 1.        ],
        ...,
        [0.        , 0.8180171 ],
        [0.        , 0.79279469],
        [0.        , 0.59136482]],

       ...,

       [[0.        , 0.80361585],
        [0.        , 0.74293529],
        [0.        , 0.8180171 ],
        ...,
        [0.        , 1.        ],
        [0.        , 0.88187117],
        [0.        , 0.66531686]],

       [[0.        , 0.81343049],
        [0.        , 0.73955261],
        [0.        , 0.79279469],
        .

In [ ]:
X = new_df['combined_matrix'].values

In [ ]:
X[0]

array([[[0.        , 1.        ],
        [0.        , 0.8016815 ],
        [0.        , 0.83964185],
        ...,
        [0.        , 0.8363548 ],
        [0.        , 0.56457186],
        [0.        , 0.34202061]],

       [[0.        , 0.8016815 ],
        [0.        , 1.        ],
        [0.        , 0.65514692],
        ...,
        [0.        , 0.72472912],
        [0.        , 0.5415269 ],
        [0.        , 0.32886773]],

       [[0.        , 0.83964185],
        [0.        , 0.65514692],
        [0.        , 1.        ],
        ...,
        [0.        , 0.76714309],
        [0.        , 0.54428893],
        [0.        , 0.34388957]],

       ...,

       [[0.        , 0.8363548 ],
        [0.        , 0.72472912],
        [0.        , 0.76714309],
        ...,
        [0.        , 1.        ],
        [0.        , 0.56476638],
        [0.        , 0.33447554]],

       [[0.        , 0.56457186],
        [0.        , 0.5415269 ],
        [0.        , 0.54428893],
        .

In [ ]:
X[0].shape

(132, 132, 2)

In [ ]:
import numpy as np
import pandas as pd

# Create a blank DataFrame with the desired columns
new_df = pd.DataFrame(columns=['subject', 'combined_matrix', 'autism', 'adhd', 'healthy'])

# Iterate over the old DataFrame using iterrows()
for i, row in data.iterrows():
    fcmap_matrix = df_norm.iloc[i]['fcmap']
    psi_matrix = row['psi_matrix']

    # Stack the matrices along a new axis (axis=2) to create a 3D matrix
    combined_matrix = np.stack((fcmap_matrix, psi_matrix), axis=2)

    # Create a temporary dictionary for the new row
    temp_dict = {
        'subject': row['subject'],
        'combined_matrix': combined_matrix,
        'autism': row['autism'],
        'adhd': row['adhd'],
        'healthy': row['healthy']
    }

    # Convert the dictionary to a Series and then to a DataFrame
    temp_df = pd.Series(temp_dict).to_frame().T
    print(temp_df)

    # Append the temporary DataFrame to the new DataFrame
    new_df = pd.concat([new_df, temp_df], ignore_index=True)
    print(new_df)

    subject                                    combined_matrix autism adhd  \
0  subject1  [[[0.0, 1.0], [0.0, 0.8016814987579317], [0.0,...      1    0   

  healthy  
0       0  
    subject                                    combined_matrix autism adhd  \
0  subject1  [[[0.0, 1.0], [0.0, 0.8016814987579317], [0.0,...      1    0   

  healthy  
0       0  
    subject                                    combined_matrix autism adhd  \
0  subject2  [[[0.0, 1.0], [0.0, 0.9101210641534417], [0.0,...      1    0   

  healthy  
0       0  
    subject                                    combined_matrix autism adhd  \
0  subject1  [[[0.0, 1.0], [0.0, 0.8016814987579317], [0.0,...      1    0   
1  subject2  [[[0.0, 1.0], [0.0, 0.9101210641534417], [0.0,...      1    0   

  healthy  
0       0  
1       0  
    subject                                    combined_matrix autism adhd  \
0  subject3  [[[0.0, 1.0], [0.0, 0.7530150385517623], [0.0,...      1    0   

  healthy  
0       0  
    s

KeyboardInterrupt: 

In [ ]:
print(type(new_df))