In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import pickle

# Save dataframe to pickled pandas object
# df.to_pickle(file_name) # where to save it usually as a .pkl

# Load dataframe from pickled pandas object
df = pd.read_pickle('/content/drive/MyDrive/Colab Notebooks/RRC_FcMaps/FCmaps_data(132x132).pkl')

print(df)

      subject                                              fcmap  adhd  \
0    subject1  [[nan, 1.0036407419797173, 0.18701701249003255...     0   
1    subject2  [[nan, 0.11609198595144368, 0.1180324429589779...     0   
2    subject3  [[nan, 0.9455449941229485, 0.08125902553011471...     0   
3    subject4  [[nan, 0.4748647287729013, 0.04488949863183865...     0   
4    subject5  [[nan, 0.29773898486020245, -0.024693109742462...     0   
..        ...                                                ...   ...   
85  subject86  [[nan, 0.05347693679181274, -0.151129236272579...     0   
86  subject87  [[nan, 0.6063083359550396, -0.3412920314564879...     0   
87  subject88  [[nan, 0.6017137014545197, 0.05437764104138904...     0   
88  subject89  [[nan, 0.26931475482245876, 0.2044951519456501...     0   
89  subject90  [[nan, 0.6373154765620194, 0.2237677212354357,...     0   

    autism  healthy  
0        1        0  
1        1        0  
2        1        0  
3        1        0  
4

In [ ]:
#Assuming your DataFrame is named df
second_column = df['fcmap']  # Selecting all rows and the third column (index 2)

print(second_column)

0     [[nan, 1.0036407419797173, 0.18701701249003255...
1     [[nan, 0.11609198595144368, 0.1180324429589779...
2     [[nan, 0.9455449941229485, 0.08125902553011471...
3     [[nan, 0.4748647287729013, 0.04488949863183865...
4     [[nan, 0.29773898486020245, -0.024693109742462...
                            ...                        
85    [[nan, 0.05347693679181274, -0.151129236272579...
86    [[nan, 0.6063083359550396, -0.3412920314564879...
87    [[nan, 0.6017137014545197, 0.05437764104138904...
88    [[nan, 0.26931475482245876, 0.2044951519456501...
89    [[nan, 0.6373154765620194, 0.2237677212354357,...
Name: fcmap, Length: 90, dtype: object


In [ ]:
# Retrieve the second column for the first row as an array
fcmaps = df.iloc[0, 1]

fcmaps.shape

(132, 132)

In [ ]:
fcmaps

array([[        nan,  1.00364074,  0.18701701, ...,  0.04738298,
        -0.00678016,  0.0218442 ],
       [ 1.00364074,         nan,  0.17991927, ...,  0.07895985,
         0.00317048, -0.06811425],
       [ 0.18701701,  0.17991927,         nan, ...,  0.16979268,
        -0.05475542,  0.04691941],
       ...,
       [ 0.04738298,  0.07895985,  0.16979268, ...,         nan,
         0.37404849,  0.30700604],
       [-0.00678016,  0.00317048, -0.05475542, ...,  0.37404849,
                nan,  0.42053992],
       [ 0.0218442 , -0.06811425,  0.04691941, ...,  0.30700604,
         0.42053992,         nan]])

In [ ]:
import numpy as np

In [ ]:
#Nan to 1

df1 = df.copy()

for idx, row in df.iterrows():
  arr = row['fcmap']
  matrix = np.nan_to_num(arr, copy = True, nan = 1.0)
  df1.at[idx, 'fcmap'] = matrix

print(df1)

      subject                                              fcmap  adhd  \
0    subject1  [[1.0, 1.0036407419797173, 0.18701701249003255...     0   
1    subject2  [[1.0, 0.11609198595144368, 0.1180324429589779...     0   
2    subject3  [[1.0, 0.9455449941229485, 0.08125902553011471...     0   
3    subject4  [[1.0, 0.4748647287729013, 0.04488949863183865...     0   
4    subject5  [[1.0, 0.29773898486020245, -0.024693109742462...     0   
..        ...                                                ...   ...   
85  subject86  [[1.0, 0.05347693679181274, -0.151129236272579...     0   
86  subject87  [[1.0, 0.6063083359550396, -0.3412920314564879...     0   
87  subject88  [[1.0, 0.6017137014545197, 0.05437764104138904...     0   
88  subject89  [[1.0, 0.26931475482245876, 0.2044951519456501...     0   
89  subject90  [[1.0, 0.6373154765620194, 0.2237677212354357,...     0   

    autism  healthy  
0        1        0  
1        1        0  
2        1        0  
3        1        0  
4

In [ ]:
# Retrieve the second column for the first row as an array
fcmaps = df1.iloc[0, 1]

fcmaps.shape

(132, 132)

In [ ]:
fcmaps

array([[ 1.        ,  1.00364074,  0.18701701, ...,  0.04738298,
        -0.00678016,  0.0218442 ],
       [ 1.00364074,  1.        ,  0.17991927, ...,  0.07895985,
         0.00317048, -0.06811425],
       [ 0.18701701,  0.17991927,  1.        , ...,  0.16979268,
        -0.05475542,  0.04691941],
       ...,
       [ 0.04738298,  0.07895985,  0.16979268, ...,  1.        ,
         0.37404849,  0.30700604],
       [-0.00678016,  0.00317048, -0.05475542, ...,  0.37404849,
         1.        ,  0.42053992],
       [ 0.0218442 , -0.06811425,  0.04691941, ...,  0.30700604,
         0.42053992,  1.        ]])

Normalising matrices

In [ ]:
# Copy the DataFrame
df_norm = df1.copy()

# Iterate over rows
for idx, row in df_norm.iterrows():
    arr = row['fcmap']

    # Perform min-max normalization
    arr_min = np.min(arr)
    arr_max = np.max(arr)
    arr_norm = (arr - arr_min) / (arr_max - arr_min)

    # Update the 'fcmap' column with the normalized matrix
    df_norm.at[idx, 'fcmap'] = arr_norm

print(df_norm)

      subject                                              fcmap  adhd  \
0    subject1  [[0.7978708787926992, 0.7994259037901399, 0.45...     0   
1    subject2  [[0.8868597040275306, 0.4243585229561212, 0.42...     0   
2    subject3  [[0.7962554818249095, 0.7701967935729389, 0.35...     0   
3    subject4  [[0.7740693970127668, 0.5458664663226054, 0.35...     0   
4    subject5  [[0.7603462077254192, 0.46401197056489074, 0.3...     0   
..        ...                                                ...   ...   
85  subject86  [[0.7586235906686478, 0.35550822308819174, 0.2...     0   
86  subject87  [[0.8126881929208227, 0.6284179597876018, 0.18...     0   
87  subject88  [[0.8272598513114905, 0.6352643738615874, 0.37...     0   
88  subject89  [[0.7748192086992796, 0.4641562634373091, 0.43...     0   
89  subject90  [[0.7158937374510388, 0.5616788300338403, 0.38...     0   

    autism  healthy  
0        1        0  
1        1        0  
2        1        0  
3        1        0  
4

In [ ]:
# Retrieve the second column for the first row as an array
fcmaps = df_norm.iloc[0, 1]


fcmaps.shape

(132, 132)

In [ ]:
fcmaps

array([[0.79787088, 0.7994259 , 0.45063153, ..., 0.39099138, 0.36785735,
        0.38008332],
       [0.7994259 , 0.79787088, 0.44759996, ..., 0.40447842, 0.37210744,
        0.34166048],
       [0.45063153, 0.44759996, 0.79787088, ..., 0.44327471, 0.34736627,
        0.39079338],
       ...,
       [0.39099138, 0.40447842, 0.44327471, ..., 0.79787088, 0.53051597,
        0.50188096],
       [0.36785735, 0.37210744, 0.34736627, ..., 0.53051597, 0.79787088,
        0.55037327],
       [0.38008332, 0.34166048, 0.39079338, ..., 0.50188096, 0.55037327,
        0.79787088]])

Padding Matrices (224 x 224)

In [ ]:
import numpy as np
import pandas as pd
import os

In [ ]:
# def pad_matrix(row):
#     arr = row['fcmap']
#     pad_top = (224 - matrix.shape[0]) // 2
#     pad_bottom = 224 - matrix.shape[0] - pad_top
#     pad_left = (224 - matrix.shape[1]) // 2
#     pad_right = 224 - matrix.shape[1] - pad_left

#     padded_matrix = np.pad(matrix, ((pad_top, pad_bottom), (pad_left, pad_right)), mode='constant')
#     return padded_matrix

# # Assuming your original DataFrame is named 'df'
# new_df = df_norm.copy()
# new_df['fcmap'] = new_df.apply(lambda row: pad_matrix(row), axis=1)

import numpy as np

def pad_matrix_df(data):
    def pad_matrix(row):
        arr = row['fcmap']
        pad_top = (224 - arr.shape[0]) // 2
        pad_bottom = 224 - arr.shape[0] - pad_top
        pad_left = (224 - arr.shape[1]) // 2
        pad_right = 224 - arr.shape[1] - pad_left
        padded_matrix = np.pad(arr, ((pad_top, pad_bottom), (pad_left, pad_right)), mode='constant')
        return padded_matrix

    df_copy = data.copy()
    df_copy['fcmap'] = df_copy.apply(lambda row: pad_matrix(row), axis=1)
    return df_copy

In [ ]:
df_pad = pad_matrix_df(df_norm)

In [ ]:
print(df_pad.shape)

(90, 5)


In [ ]:
# Get the matrix from the first row (row index 0)
matrix_row_1 = df_pad.loc[0, 'fcmap']

# Get the shape (dimensions) of the matrix
matrix_shape_row_1 = matrix_row_1.shape

print(f"The shape of the matrix in row 1 is: {matrix_shape_row_1}")

The shape of the matrix in row 1 is: (224, 224)


In [ ]:
# Get the matrix from the first row (row index 0)
matrix_row_1 = df_pad.loc[0, 'fcmap']

# Print the matrix
print(matrix_row_1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
print(df_pad)

      subject                                              fcmap  adhd  \
0    subject1  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
1    subject2  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
2    subject3  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
3    subject4  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
4    subject5  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
..        ...                                                ...   ...   
85  subject86  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
86  subject87  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
87  subject88  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
88  subject89  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   
89  subject90  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...     0   

    autism  healthy  
0        1        0  
1        1        0  
2        1        0  
3        1        0  
4

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Assuming you have the DataFrame 'df' with columns 'subject', 'fcmap', 'adhd', 'autism', 'healthy'

# Separate features (X) and labels (y)
X = df_pad['fcmap'].values
y = df_pad[['adhd', 'autism', 'healthy']].values

# Print the shapes of X and y
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (90,)
Shape of y: (90, 3)


Deep Learning Model

In [ ]:
import numpy as np

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.optimizers import Adam

In [ ]:
from keras.applications.vgg16 import preprocess_input

In [ ]:
# VGG model expects a 4D tensor as input, with the shape (batch_size, height, width, channels).
# Then preprocess the input data using preprocess_input from the keras.applications.vgg16 module, which applies the necessary preprocessing steps required by the VGG model.
X = np.stack(df_pad['fcmap'].values).reshape(-1, 224, 224)

In [ ]:
X.shape

(90, 224, 224)

In [ ]:
# Expand the last dimension to include the channel dimension
X = np.expand_dims(X, axis=-1)

In [ ]:
X.shape

(90, 224, 224, 1)

In [ ]:
# Repeat the data for each channel (RGB)
X = np.repeat(X, 3, axis=-1)
X.shape

# The line X = np.repeat(X, 3, axis=-1) repeats the data in the last dimension (the channel dimension) three times. This is necessary because the VGG pretrained model expects input data with 3 channels (RGB).

# Since your original data is a 2D matrix, it only has one channel. By repeating the data three times, you are creating a new 3D tensor with three channels, each containing the same data.

# Here is a breakdown of what the code does:

# np.repeat(X, 3, axis=-1):
# X: The input data, a 3D tensor with dimensions (batch_size, height, width, 1).
# 3: The number of times to repeat the data along the last dimension.
# axis=-1: The axis along which to repeat the data. In this case, the last dimension (channel dimension).
# The output of the code is a 3D tensor with dimensions (batch_size, height, width, 3), where each channel contains the same data as the original 2D matrix.

# This allows you to use the VGG pretrained model with your data, as it expects input data with 3 channels.

(90, 224, 224, 3)

In [ ]:
# Skipping this step (as PSI matrix contains original values)

# preprocessing according to vgg (requires 3 channels)
# X = preprocess_input(X)  # Preprocess the input data for VGG

In [ ]:
y.shape

(90, 3)

In [ ]:
X

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 

In [ ]:
y

array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1,

In [ ]:
# HOLDOUT
# from sklearn.model_selection import train_test_split

# X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.model_selection import KFold
import numpy as np

# Assuming X and y are your input data and labels
n_splits = 5  # Number of folds
kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)

for train_index, val_index in kf.split(X):
    X_train, X_val = X[train_index], X[val_index]
    y_train, y_val = y[train_index], y[val_index]

    # Build your model
    from keras.layers import Dense, Dropout, Flatten
    from keras.models import Model
    from keras.applications.vgg16 import VGG16

    base_model = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
    x = base_model.output
    x = Flatten()(x)
    x = Dense(512, activation='relu')(x)
    x = Dropout(0.5)(x)
    predictions = Dense(3, activation='softmax')(x)
    model = Model(inputs=base_model.input, outputs=predictions)

    # not performing fine tuning during training
    for layer in base_model.layers:
        layer.trainable = False

    # Compile and fit the model
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=10, batch_size=8)

    # Evaluate the model on the validation set
    val_loss, val_acc = model.evaluate(X_val, y_val)
    print(f'Validation loss: {val_loss:.4f}, Validation accuracy: {val_acc:.4f}')

58889256/58889256 [==============================] - 0s 0us/step
Epoch 1/10
9/9 [==============================] - 36s 4s/step - loss: 8.8321 - accuracy: 0.3611 - val_loss: 12.0196 - val_accuracy: 0.3333
Epoch 2/10
9/9 [==============================] - 35s 4s/step - loss: 7.2522 - accuracy: 0.3194 - val_loss: 2.3443 - val_accuracy: 0.4444
Epoch 3/10
9/9 [==============================] - 38s 4s/step - loss: 3.3203 - accuracy: 0.3611 - val_loss: 3.1809 - val_accuracy: 0.2222
Epoch 4/10
9/9 [==============================] - 41s 5s/step - loss: 2.9693 - accuracy: 0.3194 - val_loss: 1.3491 - val_accuracy: 0.3333
Epoch 5/10
9/9 [==============================] - 35s 4s/step - loss: 1.7561 - accuracy: 0.3472 - val_loss: 1.4837 - val_accuracy: 0.2222
Epoch 6/10
9/9 [==============================] - 41s 5s/step - loss: 1.2145 - accuracy: 0.4583 - val_loss: 1.1085 - val_accuracy: 0.3889
Epoch 7/10
9/9 [==============================] - 39s 5s/step - loss: 1.1286 - accuracy: 0.3889 - val_loss

fine-tuning the pre-trained weights during the training process; <br>
Unfreeze all the layers

In [ ]:
from sklearn.model_selection import KFold
import numpy as np

# Assuming X and y are your input data and labels
n_splits = 5  # Number of folds
kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)

val_losses = []
val_accuracies = []

for train_index, val_index in kf.split(X):
    X_train, X_val = X[train_index], X[val_index]
    y_train, y_val = y[train_index], y[val_index]

    # Build your model
    from keras.layers import Dense, Dropout, Flatten
    from keras.models import Model
    from keras.applications.vgg16 import VGG16

    base_model = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
    x = base_model.output
    x = Flatten()(x)
    x = Dense(512, activation='relu')(x)
    x = Dropout(0.5)(x)
    predictions = Dense(3, activation='softmax')(x)
    model = Model(inputs=base_model.input, outputs=predictions)

    # not performing fine tuning during training
    for layer in base_model.layers:
        layer.trainable = True

    # Compile and fit the model
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=10, batch_size=8)

    # Evaluate the model on the validation set
    val_loss, val_acc = model.evaluate(X_val, y_val)
    val_losses.append(val_loss)
    val_accuracies.append(val_acc)
    print(f'Validation loss: {val_loss:.4f}, Validation accuracy: {val_acc:.4f}')


# Calculate average validation loss and accuracy
avg_val_loss = sum(val_losses) / n_splits
avg_val_acc = sum(val_accuracies) / n_splits

print(f'Average validation loss: {avg_val_loss:.4f}')
print(f'Average validation accuracy: {avg_val_acc:.4f}')

Epoch 1/10
9/9 [==============================] - 104s 11s/step - loss: 3.3454 - accuracy: 0.3194 - val_loss: 1.1055 - val_accuracy: 0.2222
Epoch 2/10
9/9 [==============================] - 100s 11s/step - loss: 1.1098 - accuracy: 0.3750 - val_loss: 1.1017 - val_accuracy: 0.2222
Epoch 3/10
9/9 [==============================] - 105s 12s/step - loss: 1.0973 - accuracy: 0.3750 - val_loss: 1.1037 - val_accuracy: 0.2222
Epoch 4/10
9/9 [==============================] - 101s 11s/step - loss: 1.0969 - accuracy: 0.3750 - val_loss: 1.1060 - val_accuracy: 0.2222
Epoch 5/10
9/9 [==============================] - 101s 11s/step - loss: 1.2673 - accuracy: 0.3750 - val_loss: 1.1070 - val_accuracy: 0.2222
Epoch 6/10
9/9 [==============================] - 101s 11s/step - loss: 1.1212 - accuracy: 0.3750 - val_loss: 1.1052 - val_accuracy: 0.3333
Epoch 7/10
9/9 [==============================] - 100s 11s/step - loss: 1.1067 - accuracy: 0.2361 - val_loss: 1.1076 - val_accuracy: 0.2222
Epoch 8/10
9/9 [====

In [ ]:
# # Compile the model with a lower learning rate
# model.compile(optimizer=Adam(lr=1e-5), loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
# Train the model
# model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=20, batch_size=8)

Epoch 1/20
3/3 [==============================] - 10s 289ms/step - loss: 0.6916 - accuracy: 0.5417 - val_loss: 0.6987 - val_accuracy: 0.3333
Epoch 2/20
3/3 [==============================] - 0s 159ms/step - loss: 0.6915 - accuracy: 0.5417 - val_loss: 0.6999 - val_accuracy: 0.3333
Epoch 3/20
3/3 [==============================] - 0s 173ms/step - loss: 0.6916 - accuracy: 0.5417 - val_loss: 0.7008 - val_accuracy: 0.3333
Epoch 4/20
3/3 [==============================] - 0s 159ms/step - loss: 0.6918 - accuracy: 0.5417 - val_loss: 0.7010 - val_accuracy: 0.3333
Epoch 5/20
3/3 [==============================] - 0s 157ms/step - loss: 0.6912 - accuracy: 0.5417 - val_loss: 0.7018 - val_accuracy: 0.3333
Epoch 6/20
3/3 [==============================] - 0s 159ms/step - loss: 0.6910 - accuracy: 0.5417 - val_loss: 0.7022 - val_accuracy: 0.3333
Epoch 7/20
3/3 [==============================] - 0s 159ms/step - loss: 0.6918 - accuracy: 0.5417 - val_loss: 0.7028 - val_accuracy: 0.3333
Epoch 8/20
3/3 [===

fine-tuning the pre-trained weights during the training process; update pre-trained model's weights by training it on specific dataset - gradual unfreezing

In [ ]:
# Freeze earlier layers and only fine-tune the later layers; model learn specific features relevant to dataset, preserving generic features learned during pre-training
# Freeze all layers first
# for layer in base_model.layers:
#     layer.trainable = False

In [ ]:
# Gradual Unfreezing - progressively unfreeze earlier layers as the training progresses
# Unfreeze the last few layers
# for layer in base_model.layers[-5:]:
#     layer.trainable = True

Early stopping and other metrics

In [ ]:
from keras import metrics

f1_score = metrics.F1Score(name='f1_score')
precision = metrics.Precision(name='precision')
recall = metrics.Recall(name='recall')

In [ ]:
# Compile the model
model.compile(optimizer=Adam(lr=1e-5),
              loss='categorical_crossentropy',
              metrics=['accuracy', f1_score, precision, recall])

In [ ]:
# Check data shapes
print('X_train shape:', X_train.shape)
print('X_val shape:', X_val.shape)
print('y_train shape:', y_train.shape)
print('y_val shape:', y_val.shape)

X_train shape: (24, 224, 224, 3)
X_val shape: (6, 224, 224, 3)
y_train shape: (24,)
y_val shape: (6,)


In [ ]:
# Check data types
print('X_train dtype:', X_train.dtype)
print('X_val dtype:', X_val.dtype)
print('y_train dtype:', y_train.dtype)
print('y_val dtype:', y_val.dtype)

X_train dtype: float64
X_val dtype: float64
y_train dtype: int64
y_val dtype: int64


In [ ]:
y_train = tf.convert_to_tensor(y_train, dtype = tf.float64)
y_val = tf.convert_to_tensor(y_val, dtype = tf.float64)

In [ ]:
# Check data types
print('X_train dtype:', X_train.dtype)
print('X_val dtype:', X_val.dtype)
print('y_train dtype:', y_train.dtype)
print('y_val dtype:', y_val.dtype)

X_train dtype: float64
X_val dtype: float64
y_train dtype: <dtype: 'float64'>
y_val dtype: <dtype: 'float64'>


In [ ]:
from keras.callbacks import EarlyStopping

In [ ]:
early_stop = EarlyStopping(monitor='val_loss', patience=5)

model.fit(X_train, y_train,
          epochs=20,
          batch_size=8,
          validation_data=(X_val, y_val),
          callbacks=[early_stop])

Epoch 1/20
3/3 [==============================] - 6s 443ms/step - loss: 0.6920 - accuracy: 0.5417 - f1_score: 0.7027 - precision: 0.5417 - recall: 1.0000 - val_loss: 0.7090 - val_accuracy: 0.3333 - val_f1_score: 0.5000 - val_precision: 0.3333 - val_recall: 1.0000
Epoch 2/20
3/3 [==============================] - 0s 178ms/step - loss: 0.6887 - accuracy: 0.5417 - f1_score: 0.7027 - precision: 0.5417 - recall: 1.0000 - val_loss: 0.7093 - val_accuracy: 0.3333 - val_f1_score: 0.5000 - val_precision: 0.3333 - val_recall: 1.0000
Epoch 3/20
3/3 [==============================] - 0s 183ms/step - loss: 0.6913 - accuracy: 0.5417 - f1_score: 0.7027 - precision: 0.5417 - recall: 1.0000 - val_loss: 0.7096 - val_accuracy: 0.3333 - val_f1_score: 0.5000 - val_precision: 0.3333 - val_recall: 1.0000
Epoch 4/20
3/3 [==============================] - 1s 187ms/step - loss: 0.6927 - accuracy: 0.5417 - f1_score: 0.7027 - precision: 0.5417 - recall: 1.0000 - val_loss: 0.7096 - val_accuracy: 0.3333 - val_f1_sco

In [ ]:
model.history.history

{'loss': [0.6919839382171631,
  0.6886863708496094,
  0.6913436055183411,
  0.6927111744880676,
  0.6900506019592285,
  0.6907815933227539],
 'accuracy': [0.5416666865348816,
  0.5416666865348816,
  0.5416666865348816,
  0.5416666865348816,
  0.5416666865348816,
  0.5416666865348816],
 'f1_score': [array([0.7027027], dtype=float32),
  array([0.7027027], dtype=float32),
  array([0.7027027], dtype=float32),
  array([0.7027027], dtype=float32),
  array([0.7027027], dtype=float32),
  array([0.7027027], dtype=float32)],
 'precision': [0.5416666865348816,
  0.5416666865348816,
  0.5416666865348816,
  0.5416666865348816,
  0.5416666865348816,
  0.5416666865348816],
 'recall': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
 'val_loss': [0.7089884281158447,
  0.7093397974967957,
  0.7095756530761719,
  0.7096417546272278,
  0.7100308537483215,
  0.7103155255317688],
 'val_accuracy': [0.3333333432674408,
  0.3333333432674408,
  0.3333333432674408,
  0.3333333432674408,
  0.3333333432674408,
  0.333333343267440